import React from 'react';
import { createPortal } from "react-dom";

const MoneyReceiptPrint = ({ data }) => {
    if (!data) return null;

    return createPortal(
        <div className="hidden print:block print:fixed print:top-0 print:left-0 print:w-full print:h-full print:z-[9999] bg-white text-black p-8 font-serif leading-relaxed overflow-y-auto">
            <div className="border-4 border-gray-800 p-8 h-full relative">
                {/* Header */}
                <div className="text-center border-b-2 border-gray-800 pb-6 mb-8 group">
                    <h1 className="text-4xl font-black uppercase tracking-widest mb-2">DhakaEcommerce</h1>
                    <p className="text-sm font-semibold tracking-wider text-gray-600">PREMIUM FASHION & LIFESTYLE</p>
                    <div className="mt-4 inline-block bg-gray-800 text-white px-8 py-2 text-xl font-bold uppercase tracking-[0.2em]">Money Receipt</div>
                </div>

                {/* Receipt Details */}
                <div className="flex justify-between items-start mb-8 font-semibold">
                    <div className="space-y-2">
                        <div>Receipt No: <span className="font-mono text-lg ml-2">{data.receiptNo}</span></div>
                        <div>Date: <span className="ml-2">{new Date(data.date).toLocaleDateString()}</span></div>
                        <div>Ref: <span className="ml-2 uppercase">{data.reference || 'N/A'}</span></div>
                    </div>
                    <div className="text-right">
                        {/* Placeholder for QR or Logo if needed */}
                        <div className="text-sm text-gray-500">Authorized Copy</div>
                    </div>
                </div>

                {/* Main Content */}
                <div className="space-y-6 mb-12">
                    <div className="flex items-baseline border-b border-gray-300 pb-2">
                        <span className="w-40 font-bold uppercase text-xs tracking-wider text-gray-500">Received With Thanks From</span>
                        <span className="flex-1 font-bold text-xl px-4">{data.customerName}</span>
                    </div>

                    <div className="flex items-baseline border-b border-gray-300 pb-2">
                        <span className="w-40 font-bold uppercase text-xs tracking-wider text-gray-500">The Sum Of (Taka)</span>
                        <span className="flex-1 font-bold text-xl px-4 italic capitalize">
                            ৳ {data.amount}
                        </span>
                    </div>

                    <div className="flex items-baseline border-b border-gray-300 pb-2">
                        <span className="w-40 font-bold uppercase text-xs tracking-wider text-gray-500">Payment Mode</span>
                        <span className="flex-1 font-bold text-xl px-4 capitalize">{data.paymentMode}</span>
                    </div>
                </div>

                {/* Financial Summary Box */}
                <div className="flex justify-end mb-16">
                    <div className="w-1/2 border-2 border-gray-800 p-4 space-y-2">
                        <div className="flex justify-between items-center text-sm font-bold">
                            <span>PAID AMOUNT:</span>
                            <span className="text-xl">৳{Number(data.amount || 0)}</span>
                        </div>
                        <div className="border-t border-gray-400 my-2"></div>
                        <div className="flex justify-between items-center text-xs text-gray-600 font-semibold">
                            <span>Remaining Due:</span>
                            <span>৳{Number(data.remainingDue || 0)}</span>
                        </div>
                    </div>
                </div>

                {/* Footer / Signatures */}
                <div className="flex justify-between items-end mt-auto pt-10">
                    <div className="text-center">
                        <div className="border-t border-gray-400 w-40 mb-2"></div>
                        <span className="text-xs font-bold uppercase tracking-widest text-gray-500">Customer Signature</span>
                    </div>

                    <div className="text-center">
                        <div className="border-t border-gray-400 w-40 mb-2"></div>
                        <span className="text-xs font-bold uppercase tracking-widest text-gray-500">Authorized Signature</span>
                    </div>
                </div>

                {/* Print Date Footer */}
                <div className="absolute bottom-4 left-0 right-0 text-center text-[10px] text-gray-400 uppercase tracking-widest">
                    Generated by DhakaEcommerce System • {new Date().toLocaleString()}
                </div>
            </div>
        </div>,
        document.body
    );
};

export default MoneyReceiptPrint;
